### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mykeehu** [ill13/SpeakLocal#1]
After I installed it, I got this message. I have the latest version of oobabooga installed and I also use Google Translate extension with Hungarian language. When I received the error, the text was not translated, it remained in English. Playback controls did not appear in the chat bubbles either.

```
Traceback (most recent call last):
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 311, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 296, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 264, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "I:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 223, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "I:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 81, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "I:\oobabooga_windows\text-generation-webui\extensions\SpeakLocal\script.py", line 104, in output_modifier
    text_and_audio_data=speak_text(string)
  File "I:\oobabooga_windows\text-generation-webui\extensions\SpeakLocal\script.py", line 59, in speak_text
    tts = _TTS()
  File "I:\oobabooga_windows\text-generation-webui\extensions\SpeakLocal\script.py", line 34, in __init__
    self.engine.setProperty('voice', voices[1].id) # Set playback to the feminine voice
IndexError: list index out of range
```

**Comment by ill13** [comment]
[line 34]  ```self.engine.setProperty('voice', voices[1].id) # Set playback to the feminine voice```

I updated *script.py* to just use the 'first' voice that is installed.

Re-download or just change line 34 to ```self.engine.setProperty('voice', voices[0].id) # Set playback to the default voice```

**Comment by mykeehu** [comment]
Thank you, it works sometimes. No problem with plain text, but when I write a comment (starts with an asterisk) I get this error:

```
ERROR:pyttsx4-driver: _pump  (-2147024809, 'A paraméter nem megfelelő.', (None, None, None, 0, None))
Traceback (most recent call last):
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 311, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 296, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "I:\oobabooga_windows\text-generation-webui\modules\chat.py", line 264, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "I:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 223, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "I:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 81, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "I:\oobabooga_windows\text-generation-webui\extensions\SpeakLocal\script.py", line 106, in output_modifier
    text_and_audio_data=speak_text(string)
  File "I:\oobabooga_windows\text-generation-webui\extensions\SpeakLocal\script.py", line 67, in speak_text
    ffmpeg.input(wav_file).output(output_file, audio_bitrate='18k', loglevel="quiet" ).run()
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

I used the Regenerate button, it generated this response when it ran into an error:
`*You two leave the store and walk home, talking about all sorts of things. You notice that she's become much more talkative now that she knows she can trust you.*`

**Comment by ill13** [comment]
~~Hmm...yeah, 'special characters' [*",',*,#...*] in the generated text aren't addressed and cause the script to crash...I'll look into that!~~

Splitting this off into a separate issue
