### ISSUE TITLE
pyttsx4 module import problem

### ISSUE THREAD

**Issue by ExcessionEleven** [ill13/SpeakLocal#12]
I've installed the requirements like this 

PS C:\Users\User\Desktop\webTxtUI\extensions\SpeakLocal> pip install -r requirements.txt
Requirement already satisfied: pyttsx4 in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (3.0.15)
Requirement already satisfied: ffmpeg-python in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: six in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from pyttsx4->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: comtypes in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from pyttsx4->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: pypiwin32 in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from pyttsx4->-r requirements.txt (line 1)) (223)
Requirement already satisfied: pywin32 in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from pyttsx4->-r requirements.txt (line 1)) (306)
Requirement already satisfied: future in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from ffmpeg-python->-r requirements.txt (line 2)) (0.18.3)

when i check the version presence i see that :

PS C:\Users\User\Desktop\webTxtUI\extensions\SpeakLocal> pip show pyttsx4
Name: pyttsx4
Version: 3.0.15
Summary: Text to Speech (TTS) library for Python 3. Works without internet connection or delay. Supports multiple TTS engines, including Sapi5, nsss, and espeak.
Home-page: https://github.com/Jiangshan00001/pyttsx4
Author: Natesh M Bhat
Author-email: 710806594@qq.com
License: UNKNOWN
Location: c:\users\User\appdata\local\programs\python\python310\lib\site-packages
Requires: comtypes, pypiwin32, pywin32, six
Required-by:

But when i restart the webUI with the extension i got this : 

17:59:30-502479 INFO     Loading the extension "SpeakLocal"
17:59:30-515080 ERROR    Could not import the requirements for 'SpeakLocal'. Make sure to install the requirements for
                         the extension.

                         Linux / Mac:

                         pip install -r extensions/SpeakLocal/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\SpeakLocal\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened
                         after launching the cmd script for your OS.
17:59:30-523077 ERROR    Failed to load the extension "SpeakLocal".
Traceback (most recent call last):
  File "C:\Users\User\Desktop\webTxtUI\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\User\Desktop\webTxtUI\extensions\SpeakLocal\script.py", line 8, in <module>
    import pyttsx4
ModuleNotFoundError: No module named 'pyttsx4'

**Comment by ExcessionEleven** [comment]
I'm not a Python user, and i don't really know the environment subtilities, but i tried this in script.py :

import sys
sys.path.append(r'C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages')

And it worked, i guess there is an environnment problem somewhere
