### ISSUE TITLE
Wrong ffmpeg py package in requirement.txt!

### ISSUE THREAD

**Issue by yhyu13** [ill13/SpeakLocal#8]
I am having this error on textgen gradio webui stratup

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/root/CodeSpace/text-generation-webui/modules/chat.py", line 392, in start_new_chat
    history['visible'] += [['', apply_extensions('output', greeting, state, is_chat=True)]]
  File "/root/CodeSpace/text-generation-webui/modules/extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/root/CodeSpace/text-generation-webui/modules/extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "/root/CodeSpace/text-generation-webui/extensions/SpeakLocal/script.py", line 141, in output_modifier
    text_and_audio_data=speak_text(string)
  File "/root/CodeSpace/text-generation-webui/extensions/SpeakLocal/script.py", line 88, in speak_text
    ffmpeg.input(wav_file).output(output_file, audio_bitrate=selected_bitrate, loglevel="quiet" ).run()
AttributeError: module 'ffmpeg' has no attribute 'input'
```

You are using the wrong ffmpeg package!

https://github.com/kkroening/ffmpeg-python/issues/174#issuecomment-471158768

FYI I am using this release tag https://github.com/oobabooga/text-generation-webui/releases/tag/snapshot-2023-11-05

And latest of SpeakLocal

**Comment by ill13** [comment]
SpeakLocal is no longer working on my fresh install of Oobabooga.
The fixes list at https://github.com/kkroening/ffmpeg-python/issues/174#issuecomment-471158768 aren't working for me either
I'll have to look into this more

**Comment by ill13** [comment]
I'm not 100% happy with this answer, but it works for now

```
pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python
```
On Windows 10, make sure *ffmpeg.exe* in in your path
![image](https://github.com/ill13/SpeakLocal/assets/10509740/08816522-8614-4fd1-ba2a-df990a864248)

**Comment by ill13** [comment]
Updated requirements.txt
