### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by kalle07** [ill13/SpeakLocal#9]
all is installed fine but this error i see

**Comment by ill13** [comment]
See: https://github.com/ill13/SpeakLocal/issues/8#issuecomment-1817591817

**Comment by SencneS** [comment]
I've tried so many things from other helps. So before I submitted this issue, I uninstalled everything, cleared all folders. Installed Just the base web ui, just a standard 7B model, just SpeakLocal add-on. This is the whole error log...
Prior to this I had installed ffmpeg, and ffmpeg-python, both a windows version of both and as part of the extensions to the web-ui.
I can't work it out.

Output generated in 3.29 seconds (9.72 tokens/s, 32 tokens, context 585, seed 1540414438)
Traceback (most recent call last):
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
output = await route_utils.call_process_api(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
output = await app.get_blocks().process_api(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
result = await self.call_function(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
prediction = await utils.async_iteration(iterator)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
return await iterator.anext()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in anext
return await anyio.to_thread.run_sync(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
return await get_async_backend().run_sync_in_worker_thread(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\anyio_backends_asyncio.py", line 2144, in run_sync_in_worker_thread
return await future
^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\anyio_backends_asyncio.py", line 851, in run
result = context.run(func, *args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
return next(iterator)
^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
yield from f(*args, **kwargs)
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\modules\chat.py", line 412, in generate_chat_reply_wrapper
for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\modules\chat.py", line 380, in generate_chat_reply
for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\modules\chat.py", line 348, in chatbot_wrapper
output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\modules\extensions.py", line 231, in apply_extensions
return EXTENSION_MAP[typ](*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\modules\extensions.py", line 89, in _apply_string_extensions
text = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\extensions\SpeakLocal\script.py", line 141, in output_modifier
text_and_audio_data=speak_text(string)
^^^^^^^^^^^^^^^^^^
File "C:\Users\SencneS\Downloads\PortableGit\AI-Chatbot\text-generation-webui\extensions\SpeakLocal\script.py", line 88, in speak_text
ffmpeg.input(wav_file).output(output_file, audio_bitrate=selected_bitrate, loglevel="quiet" ).run()
^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by kalle07** [comment]
@ill13 

xtts  ... best local speak for obadooga ^^
https://github.com/kanttouchthis/text_generation_webui_xtts

**Comment by ill13** [comment]
Also see https://github.com/ill13/SpeakLocal/issues/8#issuecomment-1817591817
